/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.gradle.junitplatform;

import org.junit.jupiter.api.*;
import static org.junit.jupiter.api.Assertions.*;

import io.github.anwyho.linkedlist.ListNode;

public class LinkedListTest {
  @Test
  public void TestCreateListNode() {
    ListNode<Integer> n1 = new ListNode<Integer>(3);
  }

  @Test
  public void TestComparingListNodes() {
    ListNode<String> strA1 = new ListNode<String>("Hello, world");
    ListNode<String> strA2 = new ListNode<String>("Hello, world");
    ListNode<String> strB1 = new ListNode<String>("I'm afraid I can't");
    assertEquals(strA1.compareTo(strA2), 0);
    assertNotEquals(strA1.compareTo(strB1), 0);
  }

  @Test
  @Disabled
  public void FailingTest() {
    fail("failed");
  }
}